### ISSUE TITLE
When you build and run 'mobile_app' example for web it throws when navigating to index pages (Cupertino, Tabs, Indexed)

### ISSUE THREAD

**Issue by rydmike** [tomgilder/routemaster#115]
If I use the latest version 0.9.0-dev2 and build and run the bundled example **mobile_app** for web target and run it in Chrome, it throws the exception below during navigation. It seems to only happen when navigating to indexed pages. Also the exception was only thrown on the web build, not an Android or Widows build.

Maybe related to, or same as: https://github.com/tomgilder/routemaster/issues/110?

```
Error: Expected a value of type 'int', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:50338/dart_sdk.js:5037:11)
    at Object.castError (http://localhost:50338/dart_sdk.js:5010:15)
    at Object.cast [as as] (http://localhost:50338/dart_sdk.js:5319:17)
    at Function.as (http://localhost:50338/dart_sdk.js:18043:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:50338/dart_sdk.js:157130:75)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:50338/dart_sdk.js:157034:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50338/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:50338/dart_sdk.js:37424:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50338/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:50338/dart_sdk.js:37424:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:50338/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at setApplicationSwitcherDescription (http://localhost:50338/packages/flutter/src/services/system_chrome.dart.lib.js:321:55)
    at setApplicationSwitcherDescription.next (<anonymous>)
    at runBody (http://localhost:50338/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:50338/dart_sdk.js:37424:7)
    at Function.setApplicationSwitcherDescription (http://localhost:50338/packages/flutter/src/services/system_chrome.dart.lib.js:320:20)
    at main.TitleObserver.new.didChangeRoute (http://localhost:50338/packages/mobile_app/pages/tab_bar_page.dart.lib.js:1801:36)
    at _update (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1274:24)
    at _RouterState.new.[_setStateWithExplicitReportStatus] (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:19076:9)
    at Function.neglect (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:18912:64)
    at routemaster$.RoutemasterDelegate.new.[_updateCurrentConfiguration] (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1280:25)
    at routemaster$.RoutemasterDelegate.new.[_processNavigation] (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1328:40)
    at routemaster$.RoutemasterDelegate.new.[_initRouter] (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1304:33)
    at routemaster$.RoutemasterDelegate.new.[_rebuildRouter] (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1311:24)
    at routemaster$.RoutemasterDelegate.new.[_didChangeDependencies] (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1335:27)
    at routemaster$._RoutemasterStateTrackerState.new.didChangeDependencies (http://localhost:50338/packages/routemaster/src/system_nav_web.dart.lib.js:1713:51)
    at framework.StatefulElement.new.performRebuild (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:50029:20)
    at framework.StatefulElement.new.rebuild (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:27978:12)
    at framework.BuildOwner.new.buildScope (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:49524:55)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:50338/packages/flutter/src/widgets/widget_span.dart.lib.js:52066:77)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:50338/packages/flutter/src/rendering/layer.dart.lib.js:5054:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:50338/packages/flutter/src/scheduler/binding.dart.lib.js:717:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:50338/packages/flutter/src/scheduler/binding.dart.lib.js:689:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:50338/packages/flutter/src/scheduler/binding.dart.lib.js:646:12)
    at Object.invoke (http://localhost:50338/dart_sdk.js:175219:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:50338/dart_sdk.js:156996:15)
    at http://localhost:50338/dart_sdk.js:172643:55
```

**Comment by tomgilder** [comment]
Looks like an issue in Flutter. Comes from trying to update the page's title - I have no idea why.

**Comment by rydmike** [comment]
Weird, I did not really debug it so much yet either, but I did not see it throwing this exception on desktop/device builds, only on Web build... 🤷🏻‍♂️

**Comment by tomgilder** [comment]
Flutter issue: https://github.com/flutter/flutter/issues/83351

Will put a workaround in the demo app

**Comment by rydmike** [comment]
Thx @tomgilder, totally works! 

And that was simple enough, just an issue with the TitleObserver observer in the demo app. 

Interesting that `ApplicationSwitcherDescription` does not a accept null and that the color in the interface class is an int and not a Color. Could it not be provided there as a Color and later converted to an int, if it has to be that for the `SystemChrome` interface (which it probably has). Some other of the `SystemChrome` interface classes do that, or so I recall at least.

**Comment by tomgilder** [comment]
Feels like an API that was never supposed to be public to me :-)
