### ISSUE TITLE
[web]: Web crashing after page reload

### ISSUE THREAD

**Issue by Ahmadre** [tomgilder/routemaster#265]
At first: Thank you soo much @tomgilder for this awesome package ❤️ 

My collegue and I played around with it and he integrated it seemlessly into our production app.

But when we reload in Flutter web the page (Not the debugging reload, but the chrome windows locally!)

this happens:

```bash
Restarted application in 1.729ms.
Error: [object Event]
    at Object.createErrorWithStack ([http://localhost:42765/dart_sdk.js:5405:12]())
    at Function._throw ([http://localhost:42765/dart_sdk.js:21278:18]())
    at Function.throwWithStackTrace ([http://localhost:42765/dart_sdk.js:21272:18]())
    at async._AsyncCallbackEntry.new.callback ([http://localhost:42765/dart_sdk.js:43326:18]())
    at Object._microtaskLoop ([http://localhost:42765/dart_sdk.js:43153:13]())
    at _startMicrotaskLoop ([http://localhost:42765/dart_sdk.js:43159:13]())
    at [http://localhost:42765/dart_sdk.js:38289:9]()
```

And our screen stays black with no reasonable error `[object Event]`.

Do you have any idea?

Web-App after reload:

![Bildschirmfoto 2022-03-15 um 19 06 37](https://user-images.githubusercontent.com/18512224/158443266-fcc9537f-f1e8-4a09-ab1d-ee884719ca4f.png)

Our app.dart contains:

```dart
...
routerDelegate: RoutemasterDelegate(
  routesBuilder: (context) {
    ...

    return appNotifier.user != null
        ? loggedInMap(
            appNotifier.user!.roles,
            isSmallScreen,
          )
        : loggedOutMap(context);
  },
),
routeInformationParser: const RoutemasterParser(),
...
```

If you need any more information, please ping me.

**Comment by Ahmadre** [comment]
Seemed to be a Flutter Framework issue.
